---
- name: Deploy Web Application
  hosts: all
  become: yes
  tasks:
    - name: Run Docker container
      docker_container:
        name: simple-app
        image: sahilsaxena91096/siemens:latest
        ports:
          - "80:80"
        detach: yes
